# Segmenting and Clustering Neighborhoods in Toronto | Part-1

In [1]:
#importing libraries

import pandas as pd
import requests
from bs4 import BeautifulSoup
print("Imported!")

Imported!

In [2]:
#Using BeautifulSoup Scraping List of Postal Codes of Given Wikipedia Page

url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
extracting_data = requests.get(url).text
wiki_data = BeautifulSoup(extracting_data, 'lxml')

In [3]:
#Converting content of PostalCode HTML table as dataframe

column_names = ['Postalcode','Borough','Neighborhood']
toronto = pd.DataFrame(columns = column_names)

content = wiki_data.find('div', class_='mw-parser-output')
table = content.table.tbody
postcode = 0
borough = 0
neighborhood = 0

for tr in table.find_all('tr'):
    i = 0
    for td in tr.find_all('td'):
        if i == 0:
            postcode = td.text
            i = i + 1
        elif i == 1:
            borough = td.text
            i = i + 1
        elif i == 2: 
            neighborhood = td.text.strip('\n').replace(']','')
    toronto = toronto.append({'Postalcode': postcode,'Borough': borough,'Neighborhood': neighborhood},ignore_index=True)

In [4]:
#clean dataframe

toronto = toronto[toronto.Borough!='Not assigned']
toronto = toronto[toronto.Borough!= 0]
toronto.reset_index(drop = True, inplace = True)
i = 0
for i in range(0,toronto.shape[0]):
    if toronto.iloc[i][2] == 'Not assigned':
        toronto.iloc[i][2] = toronto.iloc[i][1]
        i = i+1

In [5]:
df = toronto.groupby(['Postalcode','Borough'])['Neighborhood'].apply(', '.join).reset_index()
df

,Postalcode,Borough,Neighborhood
0,M1A\n,Not assigned\n,Not assigned\n
1,M1B\n,Scarborough\n,"Malvern, Rouge"
2,M1C\n,Scarborough\n,"Rouge Hill, Port Union, Highland Creek"
3,M1E\n,Scarborough\n,"Guildwood, Morningside, West Hill"
4,M1G\n,Scarborough\n,Woburn
5,M1H\n,Scarborough\n,Cedarbrae
6,M1J\n,Scarborough\n,Scarborough Village
7,M1K\n,Scarborough\n,"Kennedy Park, Ionview, East Birchmount Park"
8,M1L\n,Scarborough\n,"Golden Mile, Clairlea, Oakridge"
9,M1M\n,Scarborough\n,"Cliffside, Cliffcrest, Scarborough Village West"
10,M1N\n,Scarborough\n,"Birch Cliff, Cliffside West"
11,M1P\n,Scarborough\n,"Dorset Park, Wexford Heights, Scarborough Town..."
12,M1R\n,Scarborough\n,"Wexford, Maryvale"
13,M1S\n,Scarborough\n,Agincourt
14,M1T\n,Scarborough\n,"Clarks Corners, Tam O'Shanter, Sullivan"
15,M1V\n,Scarborough\n,"Milliken, Agincourt North, Steeles East, L'Amo..."
16,M1W\n,Scarborough\n,"Steeles West, L'Amoreaux West"
17,M1X\n,Scarborough\n,Upper Rouge
18,M1Y\n,Not assigned\n,Not assigned\n
19,M1Z\n,Not assigned\n,Not assigned\n
20,M2A\n,Not assigned\n,Not assigned\n
21,M2B\n,Not assigned\n,Not assigned\n
22,M2C\n,Not assigned\n,Not assigned\n
23,M2E\n,Not assigned\n,Not assigned\n
24,M2G\n,Not assigned\n,Not assigned\n
25,M2H\n,North York\n,Hillcrest Village
26,M2J\n,North York\n,"Fairview, Henry Farm, Oriole"
27,M2K\n,North York\n,Bayview Village
28,M2L\n,North York\n,"York Mills, Silver Hills"
29,M2M\n,North York\n,"Willowdale, Newtonbrook"
...,...,...,...
150,M8N\n,Not assigned\n,Not assigned\n
151,M8P\n,Not assigned\n,Not assigned\n
152,M8R\n,Not assigned\n,Not assigned\n
153,M8S\n,Not assigned\n,Not assigned\n
154,M8T\n,Not assigned\n,Not assigned\n
155,M8V\n,Etobicoke\n,"New Toronto, Mimico South, Humber Bay Shores"
156,M8W\n,Etobicoke\n,"Alderwood, Long Branch"
157,M8X\n,Etobicoke\n,"The Kingsway, Montgomery Road, Old Mill North"
158,M8Y\n,Etobicoke\n,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
159,M8Z\n,Etobicoke\n,"Mimico NW, The Queensway West, South of Bloor,..."
160,M9A\n,Etobicoke\n,"Islington Avenue, Humber Valley Village"
161,M9B\n,Etobicoke\n,"West Deane Park, Princess Gardens, Martin Grov..."
162,M9C\n,Etobicoke\n,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
163,M9E\n,Not assigned\n,Not assigned\n
164,M9G\n,Not assigned\n,Not assigned\n
165,M9H\n,Not assigned\n,Not assigned\n
166,M9J\n,Not assigned\n,Not assigned\n
167,M9K\n,Not assigned\n,Not assigned\n
168,M9L\n,North York\n,Humber Summit
169,M9M\n,North York\n,"Humberlea, Emery"
170,M9N\n,York\n,Weston
171,M9P\n,Etobicoke\n,Westmount
172,M9R\n,Etobicoke\n,"Kingsview Village, St. Phillips, Martin Grove ..."
173,M9S\n,Not assigned\n,Not assigned\n
174,M9T\n,Not assigned\n,Not assigned\n
175,M9V\n,Etobicoke\n,"South Steeles, Silverstone, Humbergate, Jamest..."
176,M9W\n,Etobicoke\n,"Northwest, West Humber - Clairville"
177,M9X\n,Not assigned\n,Not assigned\n
178,M9Y\n,Not assigned\n,Not assigned\n
179,M9Z\n,Not assigned\n,Not assigned\n

In [6]:
df.describe()

       Postalcode         Borough    Neighborhood
count         180             180             180
unique        180              11             100
top         M1R\n  Not assigned\n  Not assigned\n
freq            1              77              77

In [8]:
#Data Cleaning: Drop None rows of df and rows having 'Not assigned' value; All "Not assigned" will be replaced by 'NaN'

df = df.dropna()
empty = 'Not assigned'
df = df[(df.Postalcode != empty ) & (df.Borough != empty) & (df.Neighborhood != empty)]
df.head()

  Postalcode         Borough                            Neighborhood
0      M1A\n  Not assigned\n                          Not assigned\n
1      M1B\n   Scarborough\n                          Malvern, Rouge
2      M1C\n   Scarborough\n  Rouge Hill, Port Union, Highland Creek
3      M1E\n   Scarborough\n       Guildwood, Morningside, West Hill
4      M1G\n   Scarborough\n                                  Woburn

In [11]:
def neighborhood_list(grouped):    
    return ', '.join(sorted(grouped['Neighborhood'].tolist()))
                    
grp = df.groupby(['Postalcode', 'Borough'])
df_2 = grp.apply(neighborhood_list).reset_index(name='Neighborhood')
df_2.describe()

       Postalcode         Borough    Neighborhood
count         180             180             180
unique        180              11             100
top         M1R\n  Not assigned\n  Not assigned\n
freq            1              77              77

In [12]:
print(df_2.shape)
df_2.head()

(180, 3)

  Postalcode         Borough                            Neighborhood
0      M1A\n  Not assigned\n                          Not assigned\n
1      M1B\n   Scarborough\n                          Malvern, Rouge
2      M1C\n   Scarborough\n  Rouge Hill, Port Union, Highland Creek
3      M1E\n   Scarborough\n       Guildwood, Morningside, West Hill
4      M1G\n   Scarborough\n                                  Woburn

In [13]:
df_2.to_csv('toronto.csv', index=False)